ALTER SCHEMA PUBLIC RENAME TO APP;

CREATE TABLE known_addresses (
  ip INTEGER NOT NULL PRIMARY KEY,
  port SMALLINT NOT NULL,
  services BIGINT NOT NULL,
  last_active TIMESTAMP WITH TIME ZONE NOT NULL
);
-- INSERT INTO KNOWN_ADDRESSES VALUES (856641869, 18333, 1037, NOW());